version: '3'
services:
  web:
    container_name: tboard-api
    build: .
    ports: 
      - "8089:8089"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: tboard-postgres
    image: postgres
    environment:
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - /postgres-volume:/var/lib/postgresql/data

volumes:
  postgresvol:
